allowBuilds:
  esbuild: true
  unrs-resolver: true

overrides:
  minimatch: "^3.1.4"
  braces: "^3.0.3"
  micromatch: "^4.0.8"
  picomatch: "^2.3.2"
  cross-spawn: "^7.0.5"
  "@babel/helpers": "^7.26.10"
  brace-expansion: "^1.1.13"
  ajv: "^6.14.0"
  serialize-javascript: "^7.0.5"
  minimist: "^1.2.8"
  json5: "^1.0.2"
  decode-uri-component: "^0.2.2"
  esbuild: "^0.28.1"
